export enum Region {
  UNSKOSANSKIKANTON = 'UnskoSanskiKanton',
  POSAVSKIKANTON = 'PosavskiKanton',
  TUZLANSKIKANTON = 'TuzlanskiKanton',
  ZENICKODOBOJSKIKANTON = 'ZenickoDobojskiKanton',
  BOSANSKOPODRINJSKIKANTON = 'BosanskoPodrinjskiKanton',
  SREDNJOBOSANSKIKANTON = 'SrednjobosanskiKanton',
  HERCEGOVACKONERETVANSKIKANTON = 'HercegovackoNeretvanskiKanton',
  ZAPADNOHERCEGOVACKIKANTON = 'ZapadnohercegovackiKanton',
  KANTONSARAJEVO = 'KantonSarajevo',
  KANTON10 = 'Kanton10',
  BANJALUCKA = 'Banjalucka',
  DOBOJBIJELJINSKA = 'DobojBijeljinska',
  SARAJEVSKOZVORNICKA = 'SarajevskoZvornicka',
  TREBINJSKOFOCANSKA = 'TrebinjskoFocanska',
  BRCKODISTRIKT = 'BrckoDistrikt',
  VANBIH = 'van-bih',
}
